#!/bin/sh

if [ "$1" = "results" ]; then
    filepath_results="results"
    if [ -d "${filepath_results}" ]; then
        rm -r "${filepath_results}"
    fi
    mkdir "${filepath_results}"
fi

filepath_temp_meshes="Mesh/Temp"
if [ -d "${filepath_temp_meshes}" ]; then
    rm -r "${filepath_temp_meshes}"
fi
mkdir "${filepath_temp_meshes}"