#!/bin/bash

current_directory="$(pwd)"

if [ "$#" -eq 0 ]; then
    echo "No argument provided. Exiting."
    exit 1
fi

if [ "$2" = "Allclean" ]; then
    bash Allclean results
else
    bash Allclean
fi

if [ "$1" = "Main" ]; then
    if [ -f "$current_directory/Main.py" ]; then
        echo ""
        echo "Running Main.yaml"
        mkdir "$current_directory/results/Main"
        python "$current_directory/Main.py"
        cp "$current_directory/Main.yaml" "$current_directory/results/Main/Main.yaml"
        cp "$current_directory/Post/Post_Template.ipynb" "$current_directory/results/Main/Post.ipynb"
        echo "Ending Simulation Main.yaml"
        echo ""
    else
        echo "Main.py not found in current directory. Exiting."
        exit 1
    fi

elif [ "$1" = "Sims" ]; then
  
    num_simulations=$(ls "$current_directory/$sims_folder"/*.yaml | wc -l)
    
    if [ "$num_simulations" -eq 0 ]; then
        echo "No YAML files found in $sims_folder. Exiting."
        exit 1
    fi
    
    sims_folder="simulations_list"
    cd "$current_directory/$sims_folder"

    sims_count=0
    
    for script_name in *.yaml
    do
        ((sims_count++))
        echo ""
        base_name="${script_name%.yaml}"
        echo "Running Simulation $sims_count : $script_name"

        mkdir "$current_directory/results/$base_name"
        python "$current_directory/Simulation.py" "$script_name"

        echo "Ending Simulation $sims_count : $script_name"
        echo ""
    done
else
    echo "Invalid argument. Available options: Main, Sims."
    exit 1
fi
